version: '3.8'

services:
  app:
    build: .
    container_name: oauth_app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: oauth_redis
    ports:
      - "6379:6379"
